export const JobCategories = [
  'Software Development',
  'Data Analysis',
  'Sales',
  'Marketing',
  'Finance',
  'Human Resources',
  'Customer Service',
  'Engineering',
  'Healthcare',
  'Education',
  'Consulting',
  'Design',
  'Operations',
  'Project Management',
  'Research',
  'Business Development',
  'Product Management',
  'Quality Assurance',
  'Legal',
  'Media and Communications',
];
